name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/frontend:latest
          ghcr.io/${{ github.repository }}/backend:latest
    
    - name: Run Docker Compose
      run: |
        echo "FRONTEND_IMAGE=ghcr.io/${{ github.repository }}/frontend:latest" > .env
        echo "BACKEND_IMAGE=ghcr.io/${{ github.repository }}/backend:latest" >> .env
        docker compose up -d
      
    - name: Wait for containers to start
      run: sleep 30
      
    - name: Check running containers
      run: docker compose ps
      
    - name: Backend health check
      run: curl -f http://localhost:5000/health || exit 1
      
    - name: Stop containers
      run: docker compose down
