name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set repository name
      run: |
        echo "REPO_NAME=sukanya0506/crud-application" >> $GITHUB_ENV
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}/frontend:latest
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: ghcr.io/${{ env.REPO_NAME }}/backend:latest
    
    - name: Run Docker Compose
      run: |
        echo "FRONTEND_IMAGE=ghcr.io/${{ env.REPO_NAME }}/frontend:latest" > .env
        echo "BACKEND_IMAGE=ghcr.io/${{ env.REPO_NAME }}/backend:latest" >> .env
        docker compose -f docker-compose.prod.yml up -d
      
    - name: Wait for containers to start
      run: sleep 30
      
    - name: Check running containers
      run: docker compose ps
      
    - name: Backend health check
      run: |
        curl -f http://localhost:5000/api/health || echo "Health check failed but continuing"
      
    - name: Stop containers
      run: docker compose down
